repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["backend"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: ["backend"]

  - repo: https://github.com/pytest-dev/pytest
    rev: v7.4.0
    hooks:
      - id: pytest
        name: pytest (unit tests)
        entry: pytest
        language: system
        types: [python]
