[project]
name = "polaris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.0.1",
    "polars>=1.25.2",
    "seaborn>=0.13.2",
    "streamlit>=1.43.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.0",
]
